service: git: Prune remote branches when updating a remote
When a branch name is reused on the remote, it may conflict with the one
tracked locally:

  error: cannot lock ref 'refs/heads/fix': 'refs/heads/fix/moss-corruption-issues' exists; cannot create 'refs/heads/fix'
  error: some local refs could not be updated; try running: 'git remote prune origin' to remove any old, conflicting branches

By pruning remote branches before updating them, we get rid of conflicts.
This is what Git itself suggests to do, but it suggests to so do
interactively. We can't afford that, because the build server would get
stuck until we prune manually.

This commit passes the `--prune` flag to prune remote branches
automatically.